version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: milestone
        no_empty:
          enabled: true
          message: 'Milestone must be specified'
      - do: project
        no_empty:
          enabled: true
          message: 'Project must be specified'
        must_include:
          # one or more chars
          regex: '.+'
    fail:
      - do: checks
        status: failure
        payload:
          title: The PR is not ready to be merged.
          summary: The pull request is not ready to be merged.
